# Generated by Django 5.0.6 on 2024-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mirror_users',
            name='api_key',
        ),
        migrations.AddField(
            model_name='mirror_users',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='mirror_users',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
