# Generated by Django 5.0.4 on 2024-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
