# Generated by Django 5.0.6 on 2024-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_mirror_users_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
