# Generated by Django 5.0.4 on 2024-04-16 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_to_do_list_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(blank=True, max_length=50, null=True)),
                ('alarm_time', models.TimeField(blank=True, null=True)),
                ('alarm_date', models.DateField(blank=True, null=True)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_mirror', to='web_app.mirror', verbose_name='Mirror_ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_users', to=settings.AUTH_USER_MODEL, verbose_name='User_ID')),
            ],
            options={
                'verbose_name': 'User Alarm',
                'db_table': 'User_mirror_bridge',
            },
        ),
    ]
