# Generated by Django 5.0.6 on 2024-05-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_to_do_list_task_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alarm',
            new_name='Bridge',
        ),
        migrations.AlterModelOptions(
            name='bridge',
            options={'verbose_name': 'User Mirror Bridge'},
        ),
    ]
