# Generated by Django 5.0.6 on 2024-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirror_users',
            name='face_pattern',
            field=models.CharField(max_length=5000),
        ),
    ]
