# Generated by Django 5.0.6 on 2024-05-14 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_mirror_users_face_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_pref',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='Topic ID')),
                ('topic', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'News Preference',
                'db_table': 'news_pref',
            },
        ),
        migrations.AlterField(
            model_name='bridge',
            name='mirrorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_mirror', to='web_app.mirror', verbose_name='Mirror ID'),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_users', to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_list', to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
        migrations.CreateModel(
            name='News_pref_Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.news_pref', verbose_name='Topic ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_users', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'News Preference Bridge',
                'db_table': 'news_pref_bridge',
            },
        ),
    ]
