# Generated by Django 5.0.6 on 2024-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_news_pref_alter_bridge_mirrorid_alter_bridge_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirror',
            name='mirror_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
