# Generated by Django 5.0.6 on 2024-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_news_pref_userid_alter_news_pref_bridge_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_pref',
            name='topic',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
