# Generated by Django 5.0.6 on 2024-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_alter_news_pref_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_pref',
            name='topic',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
