# Generated by Django 5.1.3 on 2024-11-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_news_pref_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_pref_Bridge',
        ),
    ]
